server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/corporatebank
jwt:
  secret: MyVeryStrongJWTSecretKey1234567890
  # 24 hours = 24 * 60 * 60 * 1000 = 86400000
  expiration: 86400000